spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/german_store_marketplace
    password: root

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8765/eureka