spring:
  profiles:
    active: local
  #    active: docker

  jpa:
    hibernate:
      ddl-auto: update

  application:
    name: marketplace-service

server:
  error:
    include-stacktrace: never

    port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL}