spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/german-store-marketplace
    password: root

  jpa:
    hibernate:
      ddl-auto: update

  application:
    name: marketplace-service

server:
  error:
    include-stacktrace: never

    port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8765/eureka