version: '3.9'
services:
  server:
    container_name: server
    build:
      context: ./server
    ports:
      - 8765:8765
    volumes:
      - server-volume
    networks:
      - german-net

  gateway:
    depends_on:
      - server
    container_name: gateway
    build:
      context: ./gateway
    environment:
      - EUREKA_URL=http://server:8765/eureka
    ports:
      - 8766:8766
    volumes:
      - gateway-volume
    networks:
      - german-net

  user:
    depends_on:
      - gateway
    container_name: user
    build:
      context: ./user
    environment:
      - DATABASE_URL=jdbc:postgresql://host.docker.internal:5432/german_store_user
      - EUREKA_URL=http://server:8765/eureka
    volumes:
      - user-volume
    networks:
      - german-net

  marketplace:
    depends_on:
      - gateway
      - user
    container_name: marketplace
    build:
      context: ./marketplace
    environment:
      - DATABASE_URL=jdbc:postgresql://host.docker.internal:5432/german_store_marketplace
      - EUREKA_URL=http://server:8765/eureka
    volumes:
      - marketplace-volume
    networks:
      - german-net

  transport:
    depends_on:
      - gateway
      - marketplace
    container_name: transport
    build:
      context: ./transport
    environment:
      - DATABASE_URL=jdbc:postgresql://host.docker.internal:5432/german_store_transport
      - EUREKA_URL=http://server:8765/eureka
    volumes:
      - transport-volume
    networks:
      - german-net


volumes:
  server-volume:

  gateway-volume:

  user-volume:

  marketplace-volume:

  transport-volume:


networks:
  german-net:
    driver: bridge


# DB EXAMPLE
#  marketplace-db:
#    image: postgres
#    container_name: marketplace-db
#    environment:
#      POSTGRES_PASSWORD: root
#      POSTGRES_USER: postgres
#      POSTGRES_DB: german_store_marketplace
#      POSTGRES_PORT: 6969
#    ports:
#      - 6969:6969
#    volumes:
#      - marketplace-db-volume:/var/lib/postgresql/data/
#    networks:
#      - german-net