spring:
  profiles:
#    active: local
    active: docker

  jpa:
    hibernate:
      ddl-auto: update

  application:
    name: transport-service

server:
  error:
    include-stacktrace: never

  port: 0
#  port: 8056

api:
  zipCode:
    viacep:
      endpoint: http://viacep.com.br/ws/%s/json

    melhorEnvio:
      endpoint: https://www.melhorenvio.com.br/api/v2/me/shipment/calculate
      token: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiYTZmYWQxOTFlZDM4Y2UzN2YzOGViNmY1NTRjMWRiMjBiNWZhZjNkMzkyZTZiMWExMzFhNzc3NmZmNjdiNWNjZTY3YWI2NzhlMzM5OGExZGEiLCJpYXQiOjE3MDczMzI4MDcuNjA3MjUsIm5iZiI6MTcwNzMzMjgwNy42MDcyNTEsImV4cCI6MTczODk1NTIwNy41ODU1MTksInN1YiI6IjliNDdlZDI2LTQwZmEtNDFjOC1iNmE3LWYwMGNkM2UxM2U1YiIsInNjb3BlcyI6WyJzaGlwcGluZy1jYWxjdWxhdGUiXX0.YR4xgD26EC9VWQe-8ZZWKCSvRrmZFa-GwbAQCYjvLjUDGoRQgrmLqles0nEUxHQxHkSpQkRrINnggwkT1o-TdByB3UIMsEWPGXXljCHc5LUgFqKE4-5WQrddDtv683wcJzRTRiNNF5EDOyrlGHtdRwW1ckETgG6S9ilK8WxK5c5B2IdA0X1MmnH0ZH2jAurCTDRlX6490-hw1rNYrpFeE7T1I7uM8U0Zjus4Nkcpn0pJViJZgg7FMalD-BxLKiejHmr7Zwh4eV8MflTrxsz0VLoo3s8E2N62KMukHeibMyHrrXQ9DEJBwuHd6Ru2lGCWudSGQFwBwvHMXO0SGd6GSVSnaD_VVk3G6_8oHlPrnQx5UKFZ33DtPimZpwoyFPMkzzn9oFPBNM71dW4rHRXPC9GD7gNPXP89UkIZZ48zUm_p9z8O8kgEquLCWoKHoIDQscTV1KcycPeeWxHQt2cU6yMkTicTAbU9btzZBVZ80icD3jf0x2pxhgTKv-CdQ4hxq7kSYoBf3mURtrTHduNMM3OXjhFDFAhDoMo249mBjIOw0sdIUTZx6oWsrBH2IIDyozfA0at-gHbohyAGXG02uDSFqXySTB3oei-Lhy0PhzWzp-E4fDnHSiRwBQqSnbGzeUCPlqSotLgoxNJ9ix_Dws2A9aVgQJhTL40vdSJx4_Q
      shippingCompanyZipCode: 13275090