spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5433/german-store-user
    password: root

  jpa:
    hibernate:
      ddl-auto: update

server:
  error:
    include-stacktrace: never

api:
  security:
    token:
      secret: ${JWT_SECRET:12345678}